### ISSUE TITLE
[SPEC] Persistent DKG node restarts

### ISSUE THREAD

**Issue by drewstone** [webb-tools/dkg-substrate#36]
# Overview

We want the node to be able to continue to participate in DKG after restart. Currently generated keys are stored in memory. We want to store generated keys on disk and read them upon node startup. The file contents are updated during state transitions.

# Questions

- Should we save current votes data or just discard it in case of the node restart?

# Checklist

- When the node starts:
    - Check if there is a file with DKG data.
        1. If the file is missing
            - [ ]  Try to start a new DKG process
        2. If the file is present
            - [ ]  Re-create the DKG state from that file
- When Keygen process completes:
    - Check if there is a file with DKG data.
        1. If the file is missing
            - [ ]  Create a new file
        2. If the file is present
            - [ ]  Delete old file (since we have generated new keys, we assume the old DKG epoch is over)
            - [ ]  Create a new file
- When OfflineStage process completes:
    - Check if there is a file with DKG data.
        1. If the file is missing
            - [ ]  Report the error
            - [ ]  Try to start a new DKG process
        2. If the file is present and does not contain OfflineStage
            - [ ]  Update file with OfflineStage info
        3. If the file is present and contains OfflineStage
            - [ ]  Update file with OfflineStage overriding the old OfflineStage data (we assume the signers set changed, so we discard the old OfflineStage data)
- If at any read attempt the file is corrupted:
    - [ ]  Report the error
    - [ ]  Delete the file
    - [ ]  Try start a new DKG process

**Comment by drewstone** [comment]
Artem's concerns around security of local files is relevant and we should investigate secure storage of this data. Perhaps, we prompt the user to supply a local password that encrypts the store where we put these files.

**Comment by drewstone** [comment]
We should have access as a node operator to the underlying keys I am using: SR25519 / ECDSA. Therefore, we should just use these keys to encrypt this data and store locally.

**Comment by Wizdave97** [comment]
@drewstone @temld4  
From what I understand:
Seems the only stage at which it is possible to resume  the dkg process  directly is when the Offline Stage is completed and we have the `CompletedOfflineStage` data since we only need the `CompletedOfflineStage` to sign messages,  although we need to make a PR on the multiparty-ecdsa repo so we can be able to serialize and deserialize this type.


If the node is interrupted mid `Keygen` or mid `OfflineStage`, the only way it can successfully resume and join that round, is if it has access to all the keygen or offline messages sent by the other nodes in that round.

To investigate
If one party is interrupted during the keygen or offline stage, 
1. Is the process stalled for the other participating parties or is it still able to be completed if messages from some parties are missing. I'll investigate this.
2. If the process is not stalled and the other parties somehow complete the stage.

If the process is stalled, I would propose each node holds copies of all processed messages for each stage, so that incase one party goes offline  and returns, it can request for these messages so it can proceed with the process, if the previous solution does not work out , another one  might be that the node that is just coming back online can send a message to the other nodes, so they can all restart the process.


Possibly, the values I think we need to keep on a file are the `LocalKey` so the restarting node can resume the offline stage,
 then `CompletedOfflineStage`, so the restarting node can can resume signing messages if it went off after the offline stage completed.

**Comment by Wizdave97** [comment]
From the tests I've made the Keygen stage and offline stage does not complete if a party is missing, but the process can be resumed if the party comes back online if it has access to the first batch of messages shared  among the nodes, although this is tricky in a way, from my tests with 5 parties, it needed only the first four messages from the other parties, anything beyond that led to a critical error, so i presume, we only need the first messages sent by every party for a joining party to be a able to resume the session.

There's  are some tests here https://github.com/webb-tools/dkg-substrate/tree/david/test-resuming-dkg-stages in the `dkg-primitives/rounds.rs` demonstrating this. I think we can have all nodes store the number of messages required for a joining party to resume the keygen at every stage.

**Comment by drewstone** [comment]
Sounds good. It’s worth noting that this behavior should in fact still be
considered bad and malicious. Artems work is to identify it. If it’s
identifiable before a party rejoins in time, it still creates a slashing
condition.

What are your next steps on this @david?

**Comment by Wizdave97** [comment]
I'll try to do an implementation of this on the dkg  on friday
