### ISSUE TITLE
[TASK][Testnet] Investigate ways to backup signing keys of nodes

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/dkg-substrate#684]
Currently if the DB of a running node is curropted, it loses the current active key and is unable to sign proposals, if enough of these nodes lose keys then the testnet might stall. 

Example :
```
🕸️  Signing protocol concluded with Err(GenericError { reason: "Will skip signing since local key does not exist" })
```

Goal :
- Investigate solution to backup the current active key to a seperate storage/file that can be restored even if the main DB is corrupted.

Related issue : #716

**Comment by tbraun96** [comment]
We should use [sqlx](https://docs.rs/sqlx/latest/sqlx/) with the tokio runtime feature enabled. We should also only enable `sqlite`, since, this will allow us to atomically make transactions, ensuring that if we ever ran out of disk space in the future, we wouldn't have a corrupt state.

The additional benefit to this is that we will be able to store data in a structured way.
